# Generated by Django 4.0.4 on 2022-05-31 13:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_task_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_time', models.DateTimeField(default=datetime.datetime(2022, 5, 31, 15, 45, 5, 178291))),
                ('out_time', models.DateTimeField()),
                ('total_duration', models.IntegerField()),
                ('userAtendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.DeleteModel(
            name='attendance',
        ),
    ]
